Update shell files

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,33 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION"
 
-# Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
+arch=$(uname -m)
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+	if [[ "$arch" == "x86_64" ]]; then
+		target="x86_64-unknown-linux-musl"
+	elif [[ "$arch" == "aarch64" ]]; then
+		target="aarch64-unknown-linux-musl"
+	else
+		fail "Unsupported architecture"
+	fi
+elif [[ "$OSTYPE" == "darwin"* ]]; then
+	if [[ "$arch" == "x86_64" ]]; then
+		target="x86_64-apple-darwin"
+	elif [[ "$arch" == "arm64" ]]; then
+		target="aarch64-apple-darwin"
+	else
+		fail "Unsupported architecture"
+	fi
+else
+	fail "Unsupported platform"
+fi
 
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+# Download file to the download directory
+download_release "$ASDF_INSTALL_VERSION" "$target" "$release_file"
+
+#  Move file into the download directory
+mv "$release_file" "$ASDF_DOWNLOAD_PATH/$TOOL_NAME" || fail "Could not move $release_file to $ASDF_DOWNLOAD_PATH"
+chmod +x "$ASDF_DOWNLOAD_PATH/$TOOL_NAME" || fail "Could not make $ASDF_DOWNLOAD_PATH/$TOOL_NAME executable"
